trigger:
- main
pool:
  vmImage: "Ubuntu-latest"
variables:
  acrserviceconnection: cred-ACR
  tag: '$(Build.BuildId)'
  frontendrepo: 'Credpay/frontend'
  paymentrepo: 'Credpay/payment'
  userrepo: 'Credpay/user'

stages:
  - stage: DockerBuild
    displayName: Build Docker Images
    jobs:
      - job: BuildAndPushImages
        displayName: Build Docker Images
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: 'cred-ACR'
              repository: '$(frontendrepo)'
              command: 'buildAndPush'
              Dockerfile: 'frontend-react/Dockerfile'
              buildContext: frontend-react
              tags: |
                $(tag)
                latest
          - task: Docker@2
            inputs:
              containerRegistry: 'cred-ACR'
              repository: '$(paymentrepo)'
              command: 'buildAndPush'
              Dockerfile: 'payment-service/Dockerfile'
              buildContext: payment-service
              tags: |
                $(tag)
                latest
          - task: Docker@2
            inputs:
              containerRegistry: 'cred-ACR'
              repository: '$(userrepo)'
              command: 'buildAndPush'
              Dockerfile: 'user-service/Dockerfile'
              buildContext: user-service
              tags: |
                $(tag)
                latest

                













